services:
  namenode:
    image: hadoop
    hostname: namenode
    ports:
      - 9870:9870
      - 8088:8088
      - 8983:8983
    networks:
      - hadoop
    volumes:
      - ./mrjob:/mrjob
      - ./solr:/solr
      - hadoop:/var/lib/hadoop-hdfs
    environment:
      HADOOP_MODE: namenode

  datanode:
    image: hadoop
    networks:
      - hadoop
    volumes:
      - ./mrjob:/mrjob
      - hadoop:/var/lib/hadoop-hdfs
    depends_on:
      - namenode
    environment:
      HADOOP_MODE: datanode

networks:
  hadoop:


volumes:
  hadoop:
