services:
  namenode:
    build: .
    hostname: namenode
    ports:
      - 9870:9870
      - 8088:8088
      - 8983:8983
    networks:
      - hadoop
    volumes:
      - solr:/var/lib/solr
      - hadoop:/var/lib/hadoop-hdfs
    environment:
      HADOOP_MODE: namenode
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8983
      interval: 15s
      timeout: 5s
      retries: 5

  datanode:
    build: .
    networks:
      - hadoop
    volumes:
      - solr:/var/lib/solr
      - hadoop:/var/lib/hadoop-hdfs
    depends_on:
      namenode:
        condition: service_healthy
    environment:
      HADOOP_MODE: datanode

networks:
  hadoop:


volumes:
  solr:
  hadoop:
